server:
  port: 8000
#  ssl:
#    key-store:
#    key-store-password:
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/haetae?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  banner:
    location: config/banner.txt
  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  config: classpath:config/logback.xml
wechat:
  appId:
  secret:
Yiban:
  appId: 278961da0da49b2e
  appSecret: fa224fb6224d096a957fd58ee66488c8
  redirectUri: http://127.0.0.1:5500/page/jump.html
