server:
  port: 8000
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/betahouse?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  banner:
    location: config/banner.txt
logging:
  config: classpath:config/logback.xml